config/routes.rb
Rails.application.routes.draw do
  get 'kids/resources'

  get 'contribute/howto'

  get 'playground/index'
  
  get 'mooc/education'

  get 'explore/explore'

  get 'languages/html-css'

  get 'languages/javascript'

  get 'languages/ruby'

  get 'languages/python'

  get 'languages/cpp'

  get 'languages/java'

  get 'coding_challenges/challenges'

  get 'helpful_links/links'

  get 'faq/questions'

  get 'getting_started/getting_started'

  root 'home_page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/contribute_controller.rb
class ContributeController < ApplicationController
  def howto
  end
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def explore
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def questions
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def resources
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def html_css
  end

  def javascript
  end

  def ruby
  end

  def python
  end

  def cpp
  end

  def java
  end
end

app/controllers/mooc_controller.rb
class MoocController < ApplicationController
  def education
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coding_challenges_helper.rb
module CodingChallengesHelper
end

app/helpers/contribute_helper.rb
module ContributeHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/getting_started_helper.rb
module GettingStartedHelper
end

app/helpers/helpful_links_helper.rb
module HelpfulLinksHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/mooc_helper.rb
module MoocHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Code and Learn</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= metamagic %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!--Magic CSS Animation-->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magic/1.1.0/magic.min.css" />
     <!--Devicons-->
     <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
     <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,700|Oswald|Raleway|Tangerine" rel="stylesheet">


  </head>

  <body>

    <!--Top Page border-->

    <!--Navigation-->
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Brand</a>-->
      <!---->

      <a href="/"><svg version="1.1" id="Capa_1" class="navbar-brand" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 511.856 511.856" style="enable-background:new 0 0 511.856 511.856;" xml:space="preserve">
<g>
	<g>
		<path d="M498.456,259.312l-234.667-256c-4.032-4.416-11.691-4.416-15.723,0l-234.667,256c-2.859,3.115-3.605,7.616-1.899,11.499
			c1.707,3.883,5.547,6.379,9.771,6.379h53.333v224c0,5.888,4.779,10.667,10.667,10.667h106.667c5.888,0,10.667-4.779,10.667-10.667
			v-160h106.667v160c0,5.888,4.779,10.667,10.667,10.667h106.667c5.888,0,10.667-4.779,10.667-10.667v-224h53.333
			c4.224,0,8.064-2.496,9.749-6.379C502.061,266.928,501.315,262.427,498.456,259.312z M426.605,255.856
			c-5.888,0-10.667,4.779-10.667,10.667v224h-85.333v-160c0-5.888-4.779-10.667-10.667-10.667h-128
			c-5.888,0-10.667,4.779-10.667,10.667v160H95.939v-224c0-5.888-4.779-10.667-10.667-10.667H45.528L255.939,26.309l210.411,229.547
			H426.605z"/>
	</g>
	</svg>
	</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse link_underline" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Getting Started', getting_started_getting_started_path%></li>
        <li><%=link_to 'MOOCs', mooc_education_path%></li>
        <li><%=link_to 'Helpful links', helpful_links_links_path%></li>
        <li><%=link_to 'Coding Challenges', coding_challenges_challenges_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Programming Languages<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'Html / CSS', languages_html_css_path%></li>
            <li><%=link_to 'JavaScript', languages_javascript_path%></li>
            <li><%=link_to 'Ruby', languages_ruby_path%></li>
            <li><%=link_to 'Python', languages_python_path%></li>
            <li><%=link_to 'C / C++', languages_cpp_path%></li>
            <li><%=link_to 'Java', languages_java_path%></li>
            <hr></hr>
            <li><%=link_to 'Resources for kids', kids_resources_path%></li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to 'Explore',explore_explore_path%></li>
        <li><%=link_to 'Contribute', contribute_howto_path%></li>
        <li><a href="https://github.com/Nguyen17/CodeandLearn">Github</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <div class="container">


    </div>
     <%= yield %>



  </body>
</html>